spring.application.name=otp

server.port=8060

spring.jpa.hibernate.ddl-auto=update
spring.jpa.generate-ddl=true

spring.datasource.url=jdbc:postgresql://postgres:5432/otp-db
spring.datasource.username=user1
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

logging.level.org.hibernate=INFO
logging.level.org.springframework.web=ERROR
spring.jpa.open-in-view=false

# Logs des requêtes entrantes
# logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.web.servlet.DispatcherServlet=DEBUG
spring.flyway.enabled=false
spring.flyway.locations=classpath:db/migration

spring.mail.host=localhost
spring.mail.port=2025
spring.mail.username=
spring.mail.password=
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false

# OTP Configuration
#
#otp.expiration.minutes=10
#otp.length=6
#otp.attempts=3
#otp.allowed.special.chars=false
#otp.allowed.chars=0123456789
#otp.allowed.uppercase.chars=ABCDEFGHIJKLMNOPQRSTUVWXYZ
#otp.allowed.lowercase.chars=abcdefghijklmnopqrstuvwxyz
#otp.allowed.custom.chars=
